# Generated by Django 4.2 on 2023-06-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID чата участника')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя участника')),
                ('is_speaker', models.BooleanField(default=False, verbose_name='Докладчик')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название доклада')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало доклада')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец доклада')),
                ('duration', models.DurationField(verbose_name='Длительность доклада')),
                ('speaker', models.ForeignKey(limit_choices_to={'is_speaker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bot.member', verbose_name='Доклад')),
            ],
            options={
                'verbose_name': 'Доклад',
                'verbose_name_plural': 'Доклады',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True, verbose_name='Вопрос')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Вопрос отвечен')),
                ('asker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='bot.member', verbose_name='Задавший вопрос')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bot.report', verbose_name='Презентация')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='bot.member', verbose_name='Отвечающий')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('location', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('program', models.TextField(verbose_name='Программа мероприятия')),
                ('speakers', models.ManyToManyField(related_name='events', to='bot.member', verbose_name='Список спикеров')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
