# Generated by Django 4.2 on 2023-06-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID чата участника')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя участника')),
                ('hi_speaker', models.BooleanField(default=False, verbose_name='Докладчик')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название доклада')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bot.member', verbose_name='Доклад')),
            ],
            options={
                'verbose_name': 'Доклад',
                'verbose_name_plural': 'Доклады',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True, verbose_name='Вопрос')),
                ('published_at', models.DateTimeField(verbose_name='Дата и время')),
                ('status', models.BooleanField(default=True, verbose_name='Ответили на вопрос')),
                ('asking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_questions', to='bot.member', verbose_name='Спрашивающий')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_questions', to='bot.member', verbose_name='Отвечающий')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
