# Generated by Django 4.2 on 2023-06-23 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="speaker",
            field=models.ForeignKey(
                limit_choices_to={"is_speaker": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="bot.member",
                verbose_name="Докладчик",
            ),
        ),
    ]
