# Generated by Django 4.2 on 2023-06-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="published_at",
        ),
        migrations.AddField(
            model_name="report",
            name="end_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Конец доклада"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="start_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало доклада"
            ),
        ),
    ]
