# Generated by Django 4.2 on 2023-06-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_report_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='duration',
        ),
    ]
